// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlKAFhxxoMNyr9-5I7IV7wKCfFFqed3jA',
    appId: '1:1069463213506:web:29d877b0e16007abdfb25b',
    messagingSenderId: '1069463213506',
    projectId: 'bean-counter-edc0a',
    authDomain: 'bean-counter-edc0a.firebaseapp.com',
    storageBucket: 'bean-counter-edc0a.appspot.com',
    measurementId: 'G-ES92Y1P6MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk0idfuV8R2LNjvVtO8WQUNuPdqaS63t4',
    appId: '1:1069463213506:android:9052091af8fc14aedfb25b',
    messagingSenderId: '1069463213506',
    projectId: 'bean-counter-edc0a',
    storageBucket: 'bean-counter-edc0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAobWOB0dkik9_5nTf5i-haAuoNznETTw',
    appId: '1:1069463213506:ios:0bf788cca83e186edfb25b',
    messagingSenderId: '1069463213506',
    projectId: 'bean-counter-edc0a',
    storageBucket: 'bean-counter-edc0a.appspot.com',
    iosClientId: '1069463213506-9d3io2ao6n25ogcothsp4bvvo3pt1tss.apps.googleusercontent.com',
    iosBundleId: 'com.example.beanCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAobWOB0dkik9_5nTf5i-haAuoNznETTw',
    appId: '1:1069463213506:ios:0bf788cca83e186edfb25b',
    messagingSenderId: '1069463213506',
    projectId: 'bean-counter-edc0a',
    storageBucket: 'bean-counter-edc0a.appspot.com',
    iosClientId: '1069463213506-9d3io2ao6n25ogcothsp4bvvo3pt1tss.apps.googleusercontent.com',
    iosBundleId: 'com.example.beanCounter',
  );
}
